export const initialIssues = [
{id:1,repo:'shadcn / ui',title:'Improve keyboard navigation in the date picker',summary:'Help make the date picker more accessible by improving how users navigate with their keyboard.',lang:'TypeScript',skills:['React','Accessibility'],label:'good first issue',stars:92000,color:'#171d23',mark:'↗',difficulty:'Beginner',type:'UI library'},
{id:2,repo:'freeCodeCamp / freeCodeCamp',title:'Add helpful examples to the JavaScript curriculum',summary:'Make learning a little easier. Add clear, beginner-friendly examples to an existing JavaScript lesson.',lang:'JavaScript',skills:['JavaScript','Education'],label:'first timers only',stars:425000,color:'#18233a',mark:'(f)',difficulty:'Beginner',type:'Education'},
{id:3,repo:'pallets / flask',title:'Clarify the quickstart guide for new contributors',summary:'Improve the setup instructions so first-time Flask users can get their development environment running.',lang:'Python',skills:['Python','Documentation'],label:'good first issue',stars:69000,color:'#417aac',mark:'Fl',difficulty:'Beginner',type:'Developer tools'},
{id:4,repo:'withastro / astro',title:'Fix the mobile layout of a documentation example',summary:'A small CSS fix with a big impact. Help the documentation look great on smaller screens.',lang:'TypeScript',skills:['CSS','Documentation'],label:'help wanted',stars:52000,color:'#713abf',mark:'A',difficulty:'Easy',type:'Developer tools'},
{id:5,repo:'excalidraw / excalidraw',title:'Add a tooltip to the canvas zoom controls',summary:'Give new users a little more context by adding descriptive tooltips to the zoom buttons.',lang:'TypeScript',skills:['React','Accessibility'],label:'good first issue',stars:108000,color:'#7562bd',mark:'✎',difficulty:'Beginner',type:'Web app'},
{id:6,repo:'zulip / zulip',title:'Improve the empty state for saved messages',summary:'Help people understand what to do next when their saved messages list is empty.',lang:'Python',skills:['Python','CSS'],label:'good first issue',stars:24000,color:'#4c77c0',mark:'Z',difficulty:'Easy',type:'Web app'}];
export type Issue = typeof initialIssues[number] & {url?:string;updated?:string;labels?:string[];metadataKnown?:boolean;fetchedAt?:string;comments?:number;assignees?:number;program?:string;programSource?:string};
export type Contribution = {issue:Issue;step:number;checks:Record<string,boolean>;status:'Saved'|'Exploring'|'In Progress'|'PR Submitted'|'Changes Requested'|'Merged'|'Completed';pr:string};
export const steps=[
{title:'Understand the issue',why:'A clear goal helps you avoid building the wrong thing.',body:'Read the issue and its comments. Describe the current behavior, the expected behavior, and one example. Check that no one is already working on it, then ask the maintainer whether your proposed approach fits.',command:'',mistake:'Starting to code before agreeing on the scope.',checks:['I can explain the problem in my own words','I checked the discussion and whether the issue is available']},
{title:'Understand the repository',why:'Knowing the project conventions makes your change easier to review.',body:'Read README.md for an overview, CONTRIBUTING.md for contribution rules, and the code of conduct. Search for words from the issue in the code. Follow the feature from its UI or entry point to its tests.',command:'git --version',mistake:'Assuming all projects use the same structure or tools.',checks:['I read the contribution guidelines','I identified a likely file and a related test']},
{title:'Set up the project',why:'A working local copy lets you safely reproduce the problem.',body:'Install Git, fork the repository with the Fork button on GitHub, then clone your fork. A fork is your own copy on GitHub; a clone is the copy on your computer. Replace YOUR-USERNAME below. Follow the repository’s README for its exact runtime and install commands.',command:'git clone https://github.com/YOUR-USERNAME/REPOSITORY.git\ncd REPOSITORY\ngit remote -v',mistake:'Running random install commands without checking the README or required runtime version.',checks:['I cloned my fork and followed the setup instructions','I can run the project and reproduce the issue']},
{title:'Create your branch',why:'A branch keeps this change separate from the project’s main code.',body:'Create a separate branch so your changes do not directly affect the main project. Give it a short name that explains what you are changing. Run these commands inside the cloned repository.',command:'git switch -c fix/first-contribution\ngit status',mistake:'Making unrelated changes on the same branch.',checks:['I created a branch for this issue','I confirmed my branch with git status']},
{title:'Work on the issue',why:'A small, focused change is easier to understand and review.',body:'Reproduce the original problem. Make the smallest useful change, following nearby code patterns. Revisit your example from step 1. Keep notes about why your approach works.',command:'git diff',mistake:'Refactoring unrelated code or adding extra features.',checks:['My change addresses the agreed problem','I reviewed the diff for unrelated changes']},
{title:'Test your changes',why:'Tests show your fix works and help prevent the bug from returning.',body:'Find the test instructions in CONTRIBUTING.md or the README. Run the relevant tests and the project’s formatting and lint checks. Add a regression test if appropriate. Test the original example manually too.',command:'git diff --check',mistake:'Treating a whitespace check as a substitute for the project’s test suite.',checks:['I ran the relevant project tests and checked the results','I manually verified the original problem is fixed']},
{title:'Commit & push',why:'A commit records a meaningful change. Pushing uploads it to your fork.',body:'Review git status, then stage only the files you intend to share. Replace path/to/file below with your changed file. A commit message should explain the change clearly. Never include passwords, tokens, or .env files.',command:'git status\ngit add path/to/file\ngit commit -m "fix: describe your change"\ngit push -u origin fix/first-contribution',mistake:'Staging all files without checking for secrets or generated files.',checks:['I reviewed the staged files and created a clear commit','I pushed my branch to my fork']},
{title:'Create pull request',why:'A pull request invites the project maintainers to review your work.',body:'On GitHub, open your fork and choose Compare & pull request. Check that the base is the original repository’s default branch and the head is your branch. Explain the problem, your change, and how you tested it. Follow the PR template and link the actual issue.',command:'',mistake:'Opening a PR without explaining the change or providing testing evidence.',checks:['I followed the PR template and linked the issue','I opened the PR on GitHub and copied its link below']},
{title:'Handle review',why:'Feedback is part of collaborating, not a judgment of your ability.',body:'Read each review comment carefully. Ask a focused question if anything is unclear. Make requested changes on the same branch, test them, commit, and push again. The existing PR updates automatically.',command:'git status\ngit push',mistake:'Opening a new PR for every round of feedback.',checks:['I checked the review and automated checks','I addressed feedback or confirmed that no changes are needed']},
{title:'Get merged',why:'Your contribution becomes part of a project other people use.',body:'Check that GitHub shows a purple Merged badge on your PR. Maintainers decide when to merge, so give them time. Thank the reviewers and take a moment to recognize what you learned.',command:'',mistake:'Marking a closed or still-open pull request as merged.',checks:['I verified the Merged badge on GitHub','I reflected on what I learned from my contribution']}
];
export function mentorReply(q:string,c:Contribution){const text=q.toLowerCase();if(/pr|pull request/.test(text))return `Start with this outline, then replace the brackets with what you actually did:\n\n## Summary\n[Explain your change for “${c.issue.title}”]\n\n## Why\n[Describe the original problem and link the actual issue]\n\n## Testing\n[List the commands you ran and their results]\n\nKeep the project’s PR template. Don't claim a test passed unless you ran it. What did you change and how did you verify it?`;if(/branch/.test(text))return 'A branch is a separate line of work. It lets you try a fix without changing the main project. Inside your cloned repository, run git switch -c fix/first-contribution. The -c means “create”. Then run git status to confirm your branch. What does that output say?';if(/error|npm|debug|fail|setup/.test(text))return 'Start with the first error, not the last line of the output. Compare your runtime version with the README, confirm you are in the project folder, and check the install command. For a failing test, compare the expected and actual result and try reproducing it before your change. Share the exact command and first error, with tokens removed. This demo cannot diagnose an arbitrary stack trace; those details would help a connected AI mentor or maintainer.';if(/file|structure|code/.test(text))return `For ${c.issue.repo}, begin with README.md and CONTRIBUTING.md. Search the repository for a distinctive word from “${c.issue.title}”, then look for tests referencing the same component or function. I haven't inspected this codebase, so I won't guess a filename. What files does your search return?`;if(/commit/.test(text))return `A useful commit message describes the change, for example “fix: improve keyboard navigation” only if that is what you changed. Before committing, run git diff --staged and check every file. Which behavior did your change fix?`;if(/review|feedback|approach/.test(text))return 'Compare your approach with the issue’s acceptance criteria: does it fix the reported example, preserve existing behavior, and include a relevant test? For review feedback, restate the request in your own words and ask about any ambiguity. Share your proposed change and reasoning; this demo cannot validate unseen code.';if(/issue|task|simple|understand/.test(text))return `The goal is: ${c.issue.summary}\n\nBreak it down: 1. Reproduce or locate the current behavior. 2. Write one sentence describing the expected result. 3. Find the relevant code or documentation. 4. Make one focused change. 5. Test your example.\n\nFirst, how would you explain the difference between what happens now and what should happen?`;return `You're on “${steps[c.step].title}”. ${steps[c.step].why} ${steps[c.step].body}\n\nThis is a demo teaching guide, so I can't independently analyze arbitrary questions or code. Try asking about a branch, setup error, relevant files, tests, review, or a PR description.`}
